spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/logger_db
    username: postgres
    password: empty
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres
application:
  url-address: http://localhost:8080/
